<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

$this->title = 'Easyleases';
?>

<?php if (!empty(Yii::$app->session->getFlash('owner-form-submitted'))) { ?>
    <div class="alert alert-success text-center" role="alert">
        <?= Yii::$app->session->getFlash('owner-form-submitted'); ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php } ?>

<?php if (!empty(Yii::$app->session->getFlash('owner-form-submitted-err'))) { ?>
    <div class="alert alert-danger text-center" role="alert">
        <?= Yii::$app->session->getFlash('owner-form-submitted-err'); ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php } ?>

<section id="section-1" class="terms-cond-box" style="margin-top: 100px;">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h1>
                Terms & Conditions For 3 Month’s PMS Fee Waiver Offer:
            </h1>
            <p>
                This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
            <p>
                This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.easyleases.in The domain name www.easyleases.in ("Website"), including its online services, such as use of software on Website to offer leasing and property management services for residential properties and also, provides rental property supervision and management, from rent collection, tenant relations, move in, move out assistance , bill payments and property maintenance, etc. Information, text, graphics, images and information obtained from service providers, any other website linked to this website, and any other material contained on the Website ("Materials") provided by Website is owned and operated by EASYLEASES TECHNOLOGIES PVT. LTD. (“Company”) incorporated under the provisions of the Companies Act, 2013, and having its registered office at, RG 708, Purva Riviera, Varthur Road, Bangalore 560037, where such expression shall, unless repugnant to the context thereof, be deemed to include its respective representatives, administrators, employees, directors, officers, agents and their successors and assigns.
            </p>
            <p>
                For the purpose of the following terms of use, wherever the context so requires:
            </p>
            <ul>
                <li>Company means Easyleases Technologies Pvt Ltd</li>
                <li>Customer means a property owner who is intending to engage Easyleases Technologies Pvt Ltd to manage his/her property</li>
                <li>PMS means Property Management Services; refers to the gamut of services offered by Easyleases Technologies Pvt Ltd, which are detailed in the website www.easyleases.in</li>
                <li>Offer means the waiver of the PMS fee for three (3) months</li>
            </ul>
            <p><span>1. </span> The offer is valid from 0000 HRS on 10th September 2018 till 1159 HRS on 31st December 2018. The Company can at its sole discretion decide to extend or terminate the offer before the end date without serving prior notice</p>
            <p><span>2. </span> By participating in this offer, you are agreeing to be bound by the terms & conditions herein, and also the Company’s general terms & conditions that can be found here http://easyleases.in/site/page?slug=terms-conditions</p>
            <p>
                <span>3. </span> 
                The offer is applicable only for new users. However, existing customers can avail of the offer for any new properties they may own
            <ul>
                <li>The offer is applicable only for new users. However, existing customers can avail of the offer for any new properties they may own in addition to the property(ies) for which the Company is currently rendering PMS</li>
                <li>The offer is applicable only for those customers residing in and are valid citizens of India</li>
                <li>The offer will become valid only upon a Customer signing up the Company’s Service Level Agreement (SLA) and submitting the requisite documents to the Company</li>
                <li>The said property must be managed for a minimum of 6 (six) consecutive months by the Company so as to be eligible for this offer. Customers who terminate the SLA or pull out of the PMS arrangement before completion of six consecutive months (from the date of signing up the SLA & commencement of PMS) WILL NOT be eligible for the offer</li>
                <li>
                    Exclusions
                    <ul>
                        <li>For vacant properties (without a tenant) at the time of signing up of SLA, PMS fee waiver /cashback is not applicable till the said property is rented out successfully</li>
                        <li>For properties where the tenant vacates before completion of six (6) consecutive months of PMS, fee waiver/cashback is not be applicable</li>
                    </ul>
                </li>
            </ul>
            </p>
            <p>
                <span>4. </span> Waiver Fulfilment Process: 
            <ul>
                <li>The PMS fee equivalent for 3 months will be deposited as cashback to the property owner’s bank account on completion of six (6) months of consecutive PMS. For universal understanding, PMS fee is calculated as 8.5% of the monthly rental collected from the tenant excluding maintenance charges for the property</li>
                <li>Prevailing taxes as applicable will be chargeable on the cashback</li>
            </ul>
            </p>
            <p><span>5. </span> The Company reserves all rights to modify or terminate the offer at any point in time at its sole discretion </p>
            <p><span>6. </span> The Company shall not be held liable for any interruptions to this offer due to Force Majeure or any other factor that is beyond the Company’s control </p>
            <p>
                <span>7. </span> 
                The Company reserves the right to disqualify any Customers who it believes are ineligible or violated the terms & conditions laid herein from availing this offer
            </p>
            <p><span>8. </span> The Company’s decision shall be final & binding. No correspondence in this regard shall be entertained. </p>
            <p>&nbsp;</p>
            <p>The complete terms & conditions can be found here: <a target="_blank" href="http://easyleases.in/site/page?slug=terms-conditions">here</a>.</p>
        </div>
    </div>
</section>